# **11766 Advanced Perception for Mobile Robotics**
## Master's Degree in Intelligent Systems
### University of the Balearic Islands
---

##### Write in the following the names of the members of the group:
- John Smith 1
- John Smith 2

## **Instructions**

- **Do not delete any of the provided cells or functions**. Write your code where it is indicated. You may add new cells or functions as needed to complete your work.
- Along with this assignment, please submit a comprehensive **report** in PDF format explaining your implemented solutions. This report can include, for instance:
    - A technical explanation: Clearly describe the algorithms and techniques used, including relevant code snippets.
    - Results: Present your results in a clear and concise manner. Use visualizations such as graphs or tables to enhance understanding.
    - Analysis: Interpret your results and discuss their significance. Consider, for instance, the following questions:
        - Are the results as expected? Why or why not?
        - What factors might have influenced the results?
    - Conclusions: Summarize your findings and provide overall conclusions about your project.


# **Occupancy Grid Mapping**

The aim of this assignment is to implement a 2D occupancy grid mapping algorithm as described in the lecture. We provide data recorded by a robot using a 2D laser scanner in an indoor environment. 

The raw data is arranged in the following manner:

- `poses.data`: contains the **known** robot poses as it moves around the environment. Each line corresponds to the pose of the robot at a time instant

- `ranges.data`: contains 2D laser range measurements recorded by the robot. Each line corresponds to the range measurements taken from the corresponding robot poses.

## **Log Odds to Probability**

The occupancy calculations are usually performed using the log odds. We will need to convert between log odds and probabilities in this exercise. 

**Tasks:**
- Implement the `logodds2prob` and `prob2logodds` functions in the `utils.py` file. 
- Verify that the conversion functions are correct for some test input in the following cell.

In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
# Write a code here to validate the conversion using the Log Odds
from utils import *

# Test probabilities
p = np.array([0.10, 0.35, 0.50, 0.75, 0.90])

# Forward and inverse conversion
l = prob2logodds(p)
p_recovered = logodds2prob(l)

print("Original probabilities:", p)
print("Log-odds:", np.round(l, 4))
print("Recovered probabilities:", np.round(p_recovered, 4))
print("Round-trip correct:", np.allclose(p, p_recovered, atol=1e-6))

## **Inverse Sensor Model**

The occupancy grid mapping relies on an inverse sensor model to update the occupancy of a cell in the grid. For this exercise, we consider a simple sensor model, where the occupancy of cell $m_i$ is $P_{occ}$ if the measurement $z_t$ falls in that cell, otherwise the occupancy is $P_{free}$. 

However, if the cell $m_i$ is not in the perception field, the occupancy will be $P_{prior}$.

Use the following probabilities in the implementation:
$$P_{occ} = 0.9, P_{free} = 0.35, P_{prior} = 0.5 $$

**Tasks:**
- Implement the `inv_sensor_model` function in the `utils.py` file. This function receives two points in the grid, *cell* and *endpoint*, and the corresponding probabilities of being occupied and be free ($P_{occ}$ and $P_{free}$) of the sensor. Using the provided `bresenham` function in the `utils.py`, which computes the set of cells along a straight line between two points in the grid, this function must return a list of lists, where each sublist must includes cell coordinates and its corresponding probability. To check your implementation, the output of the following code:

In [ ]:
# Input 
cell = [1,1]
endpoint = [9,9]
prob_occ = 0.9
prob_free = 0.35

#Function call for the probability output
sensor_model = inv_sensor_model(cell, endpoint, prob_occ, prob_free)
print(sensor_model)

should be:

    [[1.   1.   0.35]
     [2.   2.   0.35]
     [3.   3.   0.35]
     [4.   4.   0.35]
     [5.   5.   0.35]
     [6.   6.   0.35]
     [7.   7.   0.35]
     [8.   8.   0.35]
     [9.   9.   0.9 ]]


## **Occupancy Grid Mapping Algorithm**

Implement the occupancy grid mapping algorithm as described in the lecture slides. 

We provide some functions in the `utils.py` file to make the implementation easier.

- `ranges2cells` converts the raw measurements acquired by the robot (*ranges_raw*) into the correspoding cells of the gridmap.
- `poses2cells` converts the raw poses of the robot (*poses_raw*) into the correspoding cells of the gridmap.
- `bresenham` returns all the cells along a straigh line between two points in the gridmap.

Other parameters you may need for the implementation are provided below.

**Tasks:**
- Implement the `grid_mapping_with_known_poses` function in the `utils.py` file to compute the resulting occupancy grid map using all the measurements provided in the data. Check your implementation with the following code.

In [ ]:
import numpy as np
%matplotlib inline

map_size = 100
map_res = 0.25

prob_occ = 0.90
prob_free = 0.35
prob_prior = 0.50

# Load data
ranges_raw = np.loadtxt("data/ranges.data", delimiter=',', dtype='float')
poses_raw = np.loadtxt("data/poses.data", delimiter=',', dtype='float')

# Initialize gridmap
occ_gridmap = init_gridmap(map_size, map_res) + prob_prior
plot_gridmap(occ_gridmap)

In [ ]:
#Grid map output
gridmap = grid_mapping_with_known_poses(ranges_raw, poses_raw, occ_gridmap, map_res, prob_occ, prob_free, prob_prior)

#Plot the grid map
plot_gridmap(gridmap)